# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - run: docker build -t myapp .
      - run: docker run -d --name myapp
          -p 3000:3000
          -e JWT_SECRET=${{ secrets.JWT_SECRET }}
          -e DATABASE_URL=${{ secrets.DATABASE_URL }}
          -e EMAIL_HOST=${{ secrets.EMAIL_HOST }}
          -e EMAIL_USER=${{ secrets.EMAIL_USER }}
          -e EMAIL_PASS=${{ secrets.EMAIL_PASS }}
          sma:latest
